version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: football-bot-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - bot_network
      - traefik-public
    labels:
      - "traefik.enable=false"  # Redis should not be exposed
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  football-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: academy-bot-v2
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REDIS_URL=redis://redis:6379
      - LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - bot_network
      - traefik-public
    labels:
      - "traefik.enable=false"  # Bot doesn't need HTTP exposure
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  redis_data:
    name: football-bot-redis-data

networks:
  bot_network:
    name: football-bot-network
    driver: bridge
  traefik-public:
    external: true